global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - ct-node-exporter:9100

  - job_name: postgres
    static_configs:
      - targets:
          - ct-postgres-exporter:9187

  - job_name: redis
    static_configs:
      - targets:
          - ct-redis-exporter:9121

  - job_name: nginx
    static_configs:
      - targets:
          - ct-nginx-exporter:9113
