version: "3"

services:
  cmp-nginx:
    build: ../src/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cmp-grafana
      - cmp-redis-commander
      - cmp-adminer
      - cmp-seq
      - cmp-api

  cmp-grafana:
    build: ../src/grafana

  cmp-api:
    build:
      dockerfile: src/backend/CloudMusicPlayer.API/Dockerfile
      target: final
      context: ../
    restart: always
    ports:
      - "5229:5229"
    depends_on:
      - cmp-redis
      - cmp-postgres
    environment:
      - ASPNETCORE_HTTP_PORTS=5229
      - Encryption__Secret=${Encryption_Secret}
      - Yandex__ClientId=${Yandex_ClientId}
      - Yandex__ClientSecret=${Yandex_ClientSecret}
      - Dropbox__ClientId=${Dropbox_ClientId}
      - Dropbox__ClientSecret=${Dropbox_ClientSecret}

  cmp-redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  cmp-redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cmp-redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    depends_on:
      - cmp-redis

  cmp-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    volumes:
      - postgres-data:/data

  cmp-adminer:
    image: adminer
    restart: always

  cmp-seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=http://localhost/logs/
    volumes:
      - seq-data:/data

volumes:
  redis-data:
  seq-data:
  postgres-data:

networks:
  default:
    driver: bridge
