version: "3"

services:
  ct-nginx:
    build: ../src/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ct-grafana
      - ct-redis-commander
      - ct-adminer
      - ct-seq
      - ct-api

  ct-grafana:
    build: ../src/grafana

  ct-api:
    build:
      dockerfile: src/backend/CloudTunes.API/Dockerfile
      target: final
      context: ../
    restart: always
    ports:
      - "5229:5229"
    depends_on:
      - ct-redis
      - ct-postgres
    environment:
      - ASPNETCORE_HTTP_PORTS=5229
      - Encryption__Secret=${Encryption_Secret}
      - Yandex__ClientId=${Yandex_ClientId}
      - Yandex__ClientSecret=${Yandex_ClientSecret}
      - Dropbox__ClientId=${Dropbox_ClientId}
      - Dropbox__ClientSecret=${Dropbox_ClientSecret}

  ct-redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  ct-redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:ct-redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    depends_on:
      - ct-redis

  ct-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    volumes:
      - postgres-data:/data

  ct-adminer:
    image: adminer
    restart: always

  ct-seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=http://localhost/logs/
    volumes:
      - seq-data:/data

volumes:
  redis-data:
  seq-data:
  postgres-data:

networks:
  default:
    driver: bridge
